window._env_ = {
  REACT_APP_API_URL: "http://localhost:8010/proxy",
  REACT_APP_DJANGO_CLIENT_ID: "SBOItuB3orKBDDdMOl98Lei6q9R7G0fZKSTOOhy8",
  REACT_APP_DJANGO_CLIENT_SECRET: "4CZdlJwMKBydFiknFsAIclSoXDnDzdYCz8bvRKZfR2UQFEZYKNnJiRljWlfMPjYJ8hYkNk4WVI22qC2qDz92dGnPTZ10YMYbBuhZbQNv9OYyjFi1NNJDZ5HVGnfY7h8c",
  REACT_APP_VERSION: "2.0.0-dev",
  REACT_APP_API_KEY: "udMU1aIC.6N0BeZi9XqaDmnWIlPUDFosq29y0Axpz",
}
