server {
    listen 80;

    # Serve the static assets
    location /static/ {
        root /usr/share/nginx/html;
    }

    # Serve the environment configuration file
    location /env-config.js {
        root /usr/share/nginx/html;
    }

    # Serve the manifest.json file
    location /manifest.json {
        root /usr/share/nginx/html;
    }

    # Serve the main index.html and route non-static paths to it
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # Error handling
    error_page 404 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
