# Generated by Django 4.2 on 2024-04-17 12:12

from django.db import migrations, models
import django.db.models.deletion
import shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageTranslationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', shared.models.StatusField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source_size', models.IntegerField()),
                ('target_size', models.IntegerField(blank=True, null=True)),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('api_key', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisation.organisationapikey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
