[tool.poetry]
name = "segmenation api"
version = "0.1.0"
description = ""
authors = ["Laurens <laurens.meeus@crosslang.com>"]

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = "^0.11.3"
fastapi = "^0.100.1"
python-multipart = "^0.0.5"
#email-validator = "^1.0.5"
requests = "^2.23.0"
#celery = "^4.4.2"
#passlib = {extras = ["bcrypt"], version = "^1.7.2"}
#tenacity = "^6.1.0"
pydantic = "^2.1.1"
#emails = "^0.5.15"
#raven = "^6.10.0"
gunicorn = "^20.0.4"
