import io
from typing import List, Tuple, Generator

from lxml import etree


class Coords:
    def __init__(
        self,
        w0: float,
        h0: float,
        w1: float,
        h1: float,
        l_co: List[Tuple[float]] = None,
    ):
        self.w0 = float(w0)
        self.h0 = float(h0)
        self.w1 = float(w1)
        self.h1 = float(h1)

        self.l_co = list(map(lambda a: tuple(map(float, a)), l_co))

    @classmethod
    def from_text_region_lxml(cls, element, xmlns):
        coords = _get_unique_lxml_child(element, ".//{%s}Coords" % xmlns)

        s_l_co = coords.attrib.get("points")

        l_co = [
            tuple(map(float, s_co_i.split(",")))
            for s_co_i in s_l_co.strip().replace("  ", " ").split(" ")
        ]

        w = list(map(lambda xy: xy[0], l_co))
        h = list(map(lambda xy: xy[1], l_co))

        w0 = min(w)
        h0 = min(h)
        w1 = max(w)
        h1 = max(h)

        return cls(w0, h0, w1, h1, l_co=l_co)


def lxml_text_region_iterator(filename, ignorewordregions=False):
    p = PageXMLProcessor(filename,ignorewordregions=ignorewordregions)

    for textline in p.textline_generator():
        co = p.get_co(textline)
        text_textline = p.get_text(textline)

        yield co, text_textline


def lxml_text_region_iterator_trans(filename, target: str, ignorewordregions=False):
    """
    get all the text from the textlines after translation

    target: Language
    """

    p = PageXMLProcessor(filename,ignorewordregions=ignorewordregions)

    for textline in p.textline_generator():
        co = p.get_co(textline)
        text_textline = p.get_text_trans(textline, target=target)

        yield co, text_textline


class PageXMLProcessor:
    namespace = {
        "page-1": "http://schema.primaresearch.org/PAGE/gts/pagecontent/2013-07-15",
    }

    def __init__(self, filename, validate=False, ignorewordregions=False):
        parser = etree.XMLParser(remove_blank_text=True)
        self.element_tree = etree.parse(filename, parser)

        self.xmlns = self.element_tree.getroot().tag.split("}")[0].strip("{")

        if validate and (self.xmlns in self.namespace.values()):
            raise LookupError(
                f"Xmlns not recognised.\n{self.xmlns} not in {self.namespace.values()}"
            )

        # removing word regions makes tree processing simpler, in case these regions are not required
        if ignorewordregions: self.__remove_word_regions()

    @classmethod
    def from_string(cls, s: str, validate=False):
        with io.StringIO(s) as f:
            return cls(f, validate=validate)

    def __remove_word_regions(self):
        for textline in self.element_tree.iterfind(".//{%s}TextLine" % self.xmlns):
            for word in textline.iterfind("{%s}Word" % self.xmlns):
                textline.remove(word)

    def textline_generator(self):
        """
        Iterates over <TextLine> elements
        returns lxml elements
        """

        for region in self.element_tree.iterfind(".//{%s}TextRegion" % self.xmlns):
            # region

            for textline in region.iterfind(
                ".//{{{xmlns}}}TextLine".format(xmlns=self.xmlns)
            ):
                yield textline

    def get_co(self, textline) -> Coords:
        """
        Textline: as generated by self.textline_generator()
        returns: a Coords object
        """

        co = Coords.from_text_region_lxml(textline, self.xmlns)
        return co

    def get_text(self, textline) -> str:
        """
        Textline: as generated by self.textline_generator()
        returns: the text contained in the textline
        """

        text_textline = _get_text_from_text_region_lxml(textline, self.xmlns)
        return text_textline

    def get_text_trans(self, textline, target) -> str:
        """
        Textline: as generated by self.textline_generator()
        target: language code of target language as saved in the XML.

        returns: the text contained in the textline
        """

        text_textline = _get_text_trans_from_text_region_lxml(
            textline, self.xmlns, target
        )
        return text_textline

    def generate_paragraphs(self) -> Generator[List[str], None, None]:
        """
        returns: generator that yields paragraphs, each paragraph is a list of strings for each text line
        """

        for paragraph_el in self.element_tree.iterfind(
            ".//{%s}TextRegion" % self.xmlns
        ):
            paragraph = []
            for textline in paragraph_el.iterfind(
                ".//{{{xmlns}}}TextLine".format(xmlns=self.xmlns)
            ):
                text_textline = _get_text_from_text_region_lxml(textline, self.xmlns)
                paragraph.append(text_textline)
            yield paragraph


def _get_text_from_text_region_lxml(element, xmlns):
    path = ".//{{{xmlns}}}TextEquiv/{{{xmlns}}}Unicode".format(xmlns=xmlns)

    unicode = _get_unique_lxml_child(element, path)
    unicode_text = unicode.text
    return unicode_text.strip() if unicode_text else ""


def _get_text_trans_from_text_region_lxml(element, xmlns, target):
    # path = './/{{{xmlns}}}TextEquiv/{{{xmlns}}}trans-unit/{{{xmlns}}}target'.format(xmlns=xmlns)
    path = (
        ".//{{{xmlns}}}TextEquiv/"
        "{{{xmlns}}}trans-unit/"
        "{{{xmlns}}}target["
        "@{{http://www.w3.org/XML/1998/namespace}}lang='{target}'"
        "]".format(xmlns=xmlns, target=target)
    )
    target_el = _get_unique_lxml_child(element, path)
    target_text = target_el.text
    return target_text.strip() if target_text else ""


def _get_unique_lxml_child(element, path):
    a = list(element.iterfind(path))

    if len(a) != 1:
        raise AssertionError(f"Should only find one {path} element: {a}")

    b = a[0]

    return b
