# Generated by Django 4.2 on 2024-03-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organisation", "0001_initial"),
        ("ocr", "0001_usage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usageocr",
            name="user",
        ),
        migrations.AddField(
            model_name="usageocr",
            name="api_key",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organisation.organisationapikey",
            ),
        ),
    ]
