# Generated by Django 4.2 on 2024-03-22 07:59


import django.db.models.deletion
from django.core.management import call_command
from django.db import migrations, models


def load_ocr_engine_fixtures(apps, schema_editor):
    call_command("loaddata", "ocr_engines.json")


class Migration(migrations.Migration):
    dependencies = [
        ("ocr", "0002_change_user_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCREngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="usageocr",
            name="ocr_engine",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ocr.ocrengine",
            ),
        ),
        migrations.RunPython(load_ocr_engine_fixtures),  # Loads fixtures
    ]
